/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analytics/detections/hourly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get detections by hour
         * @description Получить детекции по часам
         */
        get: {
            parameters: {
                query?: {
                    /** @description Hours to look back */
                    hours?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"] & {
                            data?: components["schemas"]["api.DetectionsHourlyResponse"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get analytics summary
         * @description Получить сводку аналитики из ClickHouse
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"] & {
                            data?: components["schemas"]["api.AnalyticsSummaryResponse"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/top-objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get top detected objects
         * @description Получить топ обнаруженных объектов
         */
        get: {
            parameters: {
                query?: {
                    /** @description Days to look back */
                    days?: number;
                    /** @description Limit */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"] & {
                            data?: components["schemas"]["api.TopObjectsResponse"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cache/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear cache
         * @description Очистить весь кэш Redis
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/camera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get camera information
         * @description Получить информацию о камере
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"] & {
                            data?: components["schemas"]["storage.Camera"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get events list
         * @description Получить список событий системы
         */
        get: {
            parameters: {
                query?: {
                    /** @description Limit */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"] & {
                            data?: components["schemas"]["storage.Event"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get frames list
         * @description Получить список кадров
         */
        get: {
            parameters: {
                query?: {
                    /** @description Limit */
                    limit?: number;
                    /** @description Filter by detection */
                    has_detection?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"] & {
                            data?: components["schemas"]["api.FrameResponse"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Проверка работоспособности API
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recordings list
         * @description Получить список видеозаписей
         */
        get: {
            parameters: {
                query?: {
                    /** @description Limit */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"] & {
                            data?: components["schemas"]["api.RecordingResponse"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recording by ID
         * @description Получить информацию о конкретной записи
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Recording ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"] & {
                            data?: components["schemas"]["api.RecordingResponse"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get database statistics
         * @description Получить статистику базы данных
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"] & {
                            data?: {
                                [key: string]: number;
                            };
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system status
         * @description Получить полный статус системы видеонаблюдения
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"] & {
                            data?: components["schemas"]["api.StatusResponse"];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.APIResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "api.APIResponse": {
            cached?: boolean;
            data?: unknown;
            error?: string;
            message?: string;
            success?: boolean;
        };
        "api.AnalyticsSummaryResponse": {
            clickhouse_available?: boolean;
            detections_by_hour?: components["schemas"]["api.DetectionsHourlyResponse"][];
            detections_today?: number;
            top_objects?: components["schemas"]["api.TopObjectsResponse"][];
            total_detections?: number;
        };
        "api.DetectionsHourlyResponse": {
            avg_confidence?: number;
            hour?: string;
            max_confidence?: number;
            min_confidence?: number;
            object_class?: string;
            total_detections?: number;
        };
        "api.FrameResponse": {
            file_exists?: boolean;
            frame?: components["schemas"]["storage.Frame"];
            has_detection?: boolean;
            image_url?: string;
            thumbnail_url?: string;
        };
        "api.RecordingResponse": {
            download_url?: string;
            file_exists?: boolean;
            recording?: components["schemas"]["storage.Recording"];
            stream_url?: string;
        };
        "api.StatusResponse": {
            camera?: components["schemas"]["storage.Camera"];
            last_updated?: string;
            stats?: components["schemas"]["api.SystemStats"];
            system_status?: string;
            uptime?: string;
        };
        "api.SystemStats": {
            cameras?: number;
            detections?: number;
            events?: number;
            frames?: number;
            recordings?: number;
            storage_usage_bytes?: number;
        };
        "api.TopObjectsResponse": {
            avg_confidence?: number;
            object_class?: string;
            total_detections?: number;
        };
        "storage.Camera": {
            created_at?: string;
            id?: number;
            last_ping?: string;
            name?: string;
            rtsp_url?: string;
            status?: string;
            updated_at?: string;
            username?: string;
        };
        "storage.Event": {
            camera_id?: number;
            created_at?: string;
            /** @description motion, person_detected, system_error, etc */
            event_type?: string;
            id?: number;
            message?: string;
            /** @description JSON with additional data */
            metadata?: string;
            notified?: boolean;
            resolved?: boolean;
            resolved_at?: string;
            /** @description low, medium, high, critical */
            severity?: string;
            timestamp?: string;
            title?: string;
        };
        "storage.Frame": {
            camera_id?: number;
            created_at?: string;
            file_path?: string;
            file_size?: number;
            has_detection?: boolean;
            height?: number;
            id?: number;
            processed?: boolean;
            /** @description Can be null for standalone frames */
            recording_id?: number;
            thumbnail_path?: string;
            timestamp?: string;
            width?: number;
        };
        "storage.Recording": {
            archived_at?: string;
            camera_id?: number;
            /** @description h264, h265, etc */
            codec?: string;
            created_at?: string;
            /** @description seconds */
            duration?: number;
            end_time?: string;
            file_path?: string;
            file_size?: number;
            id?: number;
            /** @description 1080p, 720p, etc */
            quality?: string;
            start_time?: string;
            /** @description recording, completed, failed */
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
