FROM node:22-alpine

WORKDIR /app

# Копируем только package файлы
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы (node_modules будет игнорироваться через .dockerignore)
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]