FROM node:22-alpine

# Установка pnpm
RUN npm install -g pnpm

WORKDIR /app

# Копируем файлы для установки зависимостей
COPY package.json pnpm-lock.yaml ./

# Устанавливаем зависимости
RUN pnpm install

# Копируем остальные файлы
COPY . .

# Открываем порт
EXPOSE 5173

# Запуск dev сервера
CMD ["pnpm", "run", "dev", "--", "--host"]